2024-12-04 12:53:35.453525: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-04 12:53:35.494949: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-12-04 12:53:35.494989: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-12-04 12:53:35.496492: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-04 12:53:35.504038: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-04 12:53:35.504234: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-04 12:53:36.856608: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
  0%|          | 0/391 [00:00<?, ?it/s]  0%|          | 0/391 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/zhome/d8/f/203934/ddpm/deep_learning_ddpm_group_7/tools/train_ddpm.py", line 100, in <module>
    train(args)
  File "/zhome/d8/f/203934/ddpm/deep_learning_ddpm_group_7/tools/train_ddpm.py", line 81, in train
    loss.backward()
  File "/zhome/d8/f/203934/ddpm/deep_learning_ddpm_group_7/.venv/lib64/python3.9/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/zhome/d8/f/203934/ddpm/deep_learning_ddpm_group_7/.venv/lib64/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 15.77 GiB total capacity; 13.12 GiB already allocated; 20.19 MiB free; 14.52 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/zhome/d8/f/203934/ddpm/deep_learning_ddpm_group_7/tools/sample_ddpm.py", line 104, in <module>
    infer(args)
  File "/zhome/d8/f/203934/ddpm/deep_learning_ddpm_group_7/tools/sample_ddpm.py", line 87, in infer
    model.load_state_dict(torch.load(os.path.join(train_config['task_name'],
  File "/zhome/d8/f/203934/ddpm/deep_learning_ddpm_group_7/.venv/lib64/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/zhome/d8/f/203934/ddpm/deep_learning_ddpm_group_7/.venv/lib64/python3.9/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/zhome/d8/f/203934/ddpm/deep_learning_ddpm_group_7/.venv/lib64/python3.9/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'default_fid/ddpm_ckpt_cifar2.pth'
